// react/src/views/login/Login.js
import React, { Component } from "react";
import { connect } from "react-redux";
import { login } from "../../store/sessionStore";
import './Login.css';
import ErrorComponent from "../../tools/ErrorComponent";

class StateLogin extends ErrorComponent {
    constructor(props) {
        super(props)

        this.loginClick = this.loginClick.bind(this)
        this.cancelClick = this.cancelClick.bind(this)
        this.updateState = this.updateState.bind(this);

        this.state = {
            login: "",
            password: ""
        }
    }

    updateState(event) {
        var update = {}
        update[event.target.id] = event.target.value
        this.setState(update);
    }

    loginClick() {
        this.props.login(this.state).then(result => {
            this.props.history.push('/')
        }).catch(error => {
            this.processRestValidations(error.response.data)
        })
    }

    cancelClick() {
        this.props.history.push('/')
    }

    render() {
        return (
            <div className="login_content">
                <h2 className="global_title">Login</h2>

                <form>
                    <div className="form-group">
                        <label for="login">Usuario</label>
                        <input id="login" type="text" onChange={this.updateState} placeholder="Nombre de usuario" className={this.getErrorClass("login", "form-control")}></input>
                        <div hidden={!this.getErrorText('login')} class="invalid-feedback">{this.getErrorText('login')}</div>
                    </div>

                    <div className="form-group">
                        <label for="password">Password</label>
                        <input id="password" type="password" onChange={this.updateState} placeholder="Contrase&ntilde;a" className={this.getErrorClass("password", "form-control")}></input>
                        <div hidden={!this.getErrorText('password')} class="invalid-feedback">{this.getErrorText('password')}</div>
                    </div>

                    <div hidden={!this.errorMessage} class="alert alert-danger" role="alert">{this.errorMessage}</div>

                    <div className="btn-group ">
                        <button className="btn btn-primary" onClick={this.loginClick}>Login</button>
                        <button className="btn btn-light" onClick={this.cancelClick} >Cancel</button >
                    </div >
                </form >
            </div >
        )
    }
}

const Login = connect(
    null,
    (dispatch) => {
        return {
            login: user => login(user),
        };
    }
)(StateLogin);

export default Login

// angular/src/app/auth/login.component.ts
import { Component } from '@angular/core';
import { FormControl, FormGroup, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { AuthService } from '../auth/auth.service';
import { BasicFromGroupController } from '../tools/error.form';

@Component({
    selector: 'app-auth-login',
    templateUrl: './login.component.html'
})
export class LoginComponent extends BasicFromGroupController {
    form = new FormGroup({
        login: new FormControl('', [Validators.required]),
        password: new FormControl('', [Validators.required]),
    });

    constructor(private authService: AuthService, private router: Router) {
        super();
    }

    async submitForm() {
        this.cleanRestValidations();
        try {
            await this.authService.login(this.form.get('login').value, this.form.get('password').value);
            this.router.navigate(['/']);
        } catch (error) {
            this.processRestValidations(error);
        }
    }
}

<h2>Login</h2>

<form [formGroup]="form">
    <div class="form-group">
        <label for="login">Usuario</label>
        <input class="form-control" [class.is-invalid]="hasError('login')" id="login" formControlName="login">
        <div *ngIf="hasError('login')" class="invalid-feedback">{{getErrorText('login')}}</div>
    </div>

    <div class="form-group">
        <label for="password">Password</label>
        <input class="form-control" [class.is-invalid]="hasError('password')" id="password" formControlName="password" type="password">
        <div *ngIf="hasError('password')" class="invalid-feedback">{{getErrorText('password')}}</div>
    </div>

    <div *ngIf="errorMessage" class="alert alert-danger" role="alert">{{errorMessage}}</div>

    <div class="btn-group ">
        <button class="btn btn-primary " (click)="submitForm() " [disabled]="form.invalid ">Login</button>
        <button class="btn btn-light " [routerLink]="[ '/'] ">Cancelar</button>
    </div>
</form>
