// angular/src/app/pet/new-pet.component.ts
import { Component, OnInit } from '@angular/core';
import { FormControl, FormGroup, Validators } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { BasicFromGroupController } from '../tools/error.form';
import { PetService } from './pet.service';

@Component({
  selector: 'app-nueva-mascota',
  templateUrl: './new-pet.component.html'
})
export class NewPetComponent extends BasicFromGroupController implements OnInit {
  petId: string;

  form = new FormGroup({
    name: new FormControl('', [Validators.required]),
    description: new FormControl('', []),
    birthDate: new FormControl('', [])
  });

  constructor(
    private petService: PetService,
    private route: ActivatedRoute,
    private router: Router
  ) {
    super();
  }

  ngOnInit() {
    this.route.params.subscribe(params => {
      const id = params['id'];
      if (id) {
        this.petService
          .getPet(id)
          .then(pet => {
            this.petId = pet.id;
            this.form.get('name').setValue(pet.name);
            this.form.get('description').setValue(pet.description);
            this.form.get('birthDate').setValue(pet.birthDate);
          })
          .catch(error => {
            this.processRestValidations(error);
          });
      }
    });
  }

  submitForm() {
    this.cleanRestValidations();
    this.petService
      .savePet({
        id: this.petId,
        name: this.form.get('name').value,
        description: this.form.get('description').value,
        birthDate: this.form.get('birthDate').value
      })
      .then(mascota => this.router.navigate(['/mascotas']))
      .catch(error => this.processRestValidations(error));
  }

  onDelete() {
    this.cleanRestValidations();
    this.petService
      .deletePet(this.petId)
      .then(any => this.router.navigate(['/mascotas']))
      .catch(error => this.processRestValidations(error));
  }
}

<h2>{{mascotaId ? "Editar Mascota" : 'Nueva Mascota' }}</h2>

<form [formGroup]="form">

    <div class="form-group">
        <label for="login">Nombre</label>
        <input class="form-control" [class.is-invalid]="hasError('name')" id="name" formControlName="name">
        <div *ngIf="hasError('name')" class="invalid-feedback">{{getErrorText('name')}}</div>
    </div>

    <div class="form-group">
        <label for="login">Descripción</label>
        <input class="form-control" [class.is-invalid]="hasError('description')" id="description" formControlName="description">
        <div *ngIf="hasError('description')" class="invalid-feedback">{{getErrorText('description')}}</div>
    </div>

    <div class="form-group">
        <label for="login">Fecha Nacimiento</label>
        <input class="form-control" [class.is-invalid]="hasError('birthDate')" id="birthDate" formControlName="birthDate">
        <div *ngIf="hasError('birthDate')" class="invalid-feedback">{{getErrorText('birthDate')}}</div>
    </div>

    <div *ngIf="errorMessage" class="invalid-feedback">{{errorMessage}}</div>

    <div class="btn-group ">
        <button class="btn btn-primary" (click)="submitForm()" [disabled]="form.invalid">Guardar</button>
        <button class="btn btn-warning" *ngIf="mascotaId" (click)="onDelete()">Eliminar</button>
        <button class="btn btn-light" [routerLink]="['/mascotas']">Cancelar</button>
    </div>
</form>

// react/src/views/pets/NewPet.js
import React from "react";
import { connect } from "react-redux";
import { deletePet, savePet, newPet, loadPet } from "../../api/petsApi";
import "../../styles.css";
import CommonComponent from "../../tools/CommonComponent";
import ErrorLabel from "../../tools/ErrorLabel";

class StateNewPet extends CommonComponent {
    constructor(props) {
        super(props);

        this.state = {
            id: "",
            name: "",
            description: "",
            birthDate: "",
        };
    }

    componentDidMount() {
        const { id } = this.props.match.params;
        if (id) {
            loadPet(id).then(result => {
                this.setState(result);
            }).catch(error => {
                this.processRestValidations(error);
            });
        }
    }

    deleteClick = () => {
        if (this.state.id) {
            this.props.deletePet(this.state.id).then(result => {
                this.props.history.push("/pets");
            }).catch(error => {
                this.processRestValidations(error);
            });
        }
    }

    saveClick = () => {
        this.cleanRestValidations();
        if (!this.state.name) {
            this.addError("name", "No puede estar vacío");
        }

        if (this.hasErrors()) {
            this.forceUpdate();
            return;
        }

        if (this.state.id) {
            this.props.savePet(this.state).then(result => {
                this.props.history.push("/pets");
            }).catch(error => {
                this.processRestValidations(error);
            });
        } else {
            this.props.newPet(this.state).then(result => {
                this.props.history.push("/pets");
            }).catch(error => {
                this.processRestValidations(error);
            });
        }
    }

    render() {
        return (
            <div className="global_content">
                <h2 className="global_title">Nueva Mascota</h2>

                <form>
                    <div className="form-group">
                        <label>Nombre</label>
                        <input id="name" type="text" value={this.state.name} onChange={this.updateState} className={this.getErrorClass("name", "form-control")}></input>
                        <ErrorLabel error={this.getErrorText("name")} />
                    </div>

                    <div className="form-group">
                        <label>Descripción</label>
                        <input id="description" type="text" value={this.state.description} onChange={this.updateState} className={this.getErrorClass("description", "form-control")}></input>
                        <ErrorLabel error={this.getErrorText("description")} />
                    </div>

                    <div className="form-group">
                        <label>Fecha de Nacimiento</label>
                        <input id="birthDate" type="text" value={this.state.birthDate} onChange={this.updateState} className={this.getErrorClass("birthDate", "form-control")}></input>
                        <ErrorLabel error={this.getErrorText("birthDate")} />
                    </div>

                    <div hidden={!this.errorMessage} className="alert alert-danger" role="alert">{this.errorMessage}</div>

                    <div className="btn-group ">
                        <button className="btn btn-primary" onClick={this.saveClick}>Guardar</button>
                        <button hidden={!this.state.id} className="btn btn-warning" onClick={this.deleteClick}>Eliminar</button>
                        <button className="btn btn-light" onClick={this.goHome} >Cancelar</button >
                    </div >
                </form >
            </div>
        );
    }
}

const NewPet = connect(
    null,
    (dispatch) => {
        return {
            deletePet: id => deletePet(id),
            newPet: pet => newPet(pet),
            savePet: pet => savePet(pet),
            loadPet: id => loadPet(id)
        };
    }
)(StateNewPet);

export default NewPet;
