// react/src/views/profile/Profile.tsx
import React from "react";
// tslint:disable-next-line:max-line-length
import { getCurrentProfile, getPictureUrl, updateBasicInfo, updateProfilePicture } from "../../api/profileApi";
import { getProvinces, IProvince } from "../../api/provincesApi";
import "../../styles.css";
import CommonComponent, { ICommonProps } from "../../tools/CommonComponent";
import ErrorLabel from "../../tools/ErrorLabel";
import ImageUpload from "../../tools/ImageUpload";

interface IState {
    name: string;
    province: string;
    email: string;
    address: string;
    phone: string;
    picture: string;
    provinces: IProvince[];
}

export default class Profile extends CommonComponent<ICommonProps, IState> {
    constructor(props: ICommonProps) {
        super(props);

        this.state = {
            address: "",
            email: "",
            name: "",
            phone: "",
            picture: "",
            province: "",
            provinces: [],
        };

        this.getProvinces();
        this.loadProfile();
    }

    public async getProvinces() {
        try {
            const result = await getProvinces();
            this.setState({
                provinces: result,
            });
        } catch (error) {
            this.processRestValidations(error);
        }
    }

    public async loadProfile() {
        try {
            const result = await getCurrentProfile();
            this.setState(result);
        } catch (error) {
            this.processRestValidations(error);
        }
    }

    public uploadPicture = async (image: string) => {
        try {
            const result = await updateProfilePicture({
                image,
            });
            this.setState({
                picture: result.id,
            });
        } catch (error) {
            this.processRestValidations(error);
        }
    }

    public updateClick = async () => {
        this.cleanRestValidations();
        if (!this.state.name) {
            this.addError("name", "No puede estar vacío");
        }
        if (!this.state.email) {
            this.addError("email", "No puede estar vacío");
        }
        if (this.hasErrors()) {
            this.forceUpdate();
            return;
        }

        try {
            await updateBasicInfo(
                {
                    address: this.state.address,
                    email: this.state.email,
                    name: this.state.name,
                    phone: this.state.phone,
                    province: this.state.province,
                },
            );
            this.props.history.push("/");
        } catch (error) {
            this.processRestValidations(error);
        }
    }

    public render() {
        return (
            <div className="global_content">
                <h2 className="global_title">Actualizar Perfil</h2>

                <form onSubmit={(e) => e.preventDefault()}>
                    <div className="form-group">
                        <label>Nombre</label>
                        <input id="name" type="text"
                            value={this.state.name}
                            onChange={this.updateState}
                            className={this.getErrorClass("name", "form-control")}>
                        </input>
                        <ErrorLabel error={this.getErrorText("name")} />
                    </div>

                    <div className="form-group">
                        <label>Profile Picture</label>
                        <ImageUpload src={getPictureUrl(this.state.picture)}
                            onChange={this.uploadPicture} />
                        <ErrorLabel error={this.getErrorText("name")} />
                    </div>

                    <div className="form-group">
                        <label>Email</label>
                        <input id="email" type="text"
                            value={this.state.email}
                            onChange={this.updateState}
                            className={this.getErrorClass("email", "form-control")}>
                        </input>
                        <ErrorLabel error={this.getErrorText("email")} />
                    </div>

                    <div className="form-group">
                        <label>Provincia</label>
                        <select
                            value={this.state.province}
                            onChange={(e) => this.setState({ province: e.target.value })}
                            className={this.getErrorClass("email", "form-control")}>
                            {this.state.provinces.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}
                        </select>
                        <ErrorLabel error={this.getErrorText("province")} />
                    </div>

                    <div className="form-group">
                        <label>Dirección</label>
                        <input id="address" type="text"
                            value={this.state.address}
                            onChange={this.updateState}
                            className={this.getErrorClass("address", "form-control")}>
                        </input>
                        <ErrorLabel error={this.getErrorText("address")} />
                    </div>

                    <div className="form-group">
                        <label>Tel&eacute;fono</label>
                        <input id="phone" type="text"
                            value={this.state.phone}
                            onChange={this.updateState}
                            className={this.getErrorClass("phone", "form-control")}>
                        </input>
                        <ErrorLabel error={this.getErrorText("phone")} />
                    </div>

                    <div hidden={!this.errorMessage}
                        className="alert alert-danger"
                        role="alert">{this.errorMessage}
                    </div>

                    <div className="btn-group ">
                        <button className="btn btn-primary" onClick={this.updateClick}>Actualizar</button>
                        <button className="btn btn-light" onClick={this.goHome} >Cancelar</button >
                    </div >
                </form >
            </div>
        );
    }
}

// angular/src/app/profile/profile.component.ts
import { Component, OnInit } from '@angular/core';
import { FormControl, FormGroup, Validators } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { environment } from 'src/environments/environment';
import { Province, ProvinceService } from '../province/province.service';
import { BasicFromGroupController } from '../tools/error.form';
import { ImageService } from '../image/image.service';
import { Profile, ProfileService } from './profile.service';

@Component({
  selector: 'app-perfil',
  templateUrl: './profile.component.html'
})
export class ProfileComponent extends BasicFromGroupController implements OnInit {
  newImage: string;
  provinces: Province[];
  profile: Profile;

  form = new FormGroup({
    name: new FormControl('', [Validators.required]),
    picture: new FormControl('/assets/select_image.png'),
    email: new FormControl('', [Validators.required]),
    address: new FormControl('', [Validators.required]),
    phone: new FormControl('', [Validators.required]),
    province: new FormControl('', [])
  });

  constructor(
    private provinceService: ProvinceService,
    private profileService: ProfileService,
    private imageService: ImageService,
    private route: ActivatedRoute,
    private router: Router
  ) {
    super();
    this.profile = {
      name: '',
      email: '',
      province: '',
      address: '',
      picture: '',
      phone: ''
    };
  }

  updateImage(imagen: string) {
    if (imagen.indexOf(environment.serverBase) < 0) {
      this.newImage = imagen;
    }
  }

  async ngOnInit() {
    try {
      this.provinces = await this.provinceService.getProvinces();
      this.profile = await this.profileService.findProfile();
      this.form.get('name').setValue(this.profile.name);
      this.form.get('email').setValue(this.profile.email);
      this.form.get('address').setValue(this.profile.address);
      this.form.get('phone').setValue(this.profile.phone);
      if (this.profile.province) {
        this.form.get('province').setValue(this.profile.province);
      }
      if (this.profile.picture) {
        this.form.get('picture').setValue(this.imageService.imageUrl(this.profile.picture));
      }
    } catch (error) {
      this.processRestValidations(error);
    }
  }

  async submitForm() {
    this.cleanRestValidations();

    try {
      if (this.newImage) {
        const imagen = await this.imageService.saveImage({ image: this.newImage });
        this.profile.picture = imagen.id;
      }

      this.profile.address = this.form.get('address').value;
      this.profile.name = this.form.get('name').value;
      this.profile.email = this.form.get('email').value;
      this.profile.province = this.form.get('province').value;
      this.profile.phone = this.form.get('phone').value;

      await this.profileService.saveProfile(this.profile);
      this.router.navigate(['/']);
    } catch (error) {
      this.processRestValidations(error);
    }
  }
}

<h2>Perfil</h2>

<form [formGroup]="form">

    <div class="form-group">
        <label for="login">Nombre</label>
        <input class="form-control" [class.is-invalid]="hasError('name')" id="name" formControlName="name">
        <div *ngIf="hasError('name')" class="invalid-feedback">{{getErrorText('name')}}</div>
    </div>

    <div class="form-group">
        <label for="name">Imagen</label><BR>

        <app-file-upload allowedTypes="image/*" uploadButtonText="Upload File" formControlName="picture"
            (ngModelChange)="updateImage($event)">
        </app-file-upload>

        <div *ngIf="hasError('picture')" class="invalid-feedback">{{getErrorText('picture')}}</div>
    </div>

    <div class="form-group">
        <label for="login">Email</label>
        <input class="form-control" [class.is-invalid]="hasError('email')" id="email" formControlName="email">
        <div *ngIf="hasError('email')" class="invalid-feedback">{{getErrorText('email')}}</div>
    </div>

    <div class="form-group">
        <label for="login">Provincia</label>
        <select class="form-control" [class.is-invalid]="hasError('province')" formControlName="province">
            <option *ngFor="let item of provinces" [value]="item.id">{{item.name}}</option>
        </select>

        <div *ngIf="hasError('province')" class="invalid-feedback">{{getErrorText('province')}}</div>
    </div>

    <div class="form-group">
        <label for="login">Dirección</label>
        <input class="form-control" [class.is-invalid]="hasError('address')" id="address" formControlName="address">
        <div *ngIf="hasError('address')" class="invalid-feedback">{{getErrorText('address')}}</div>
    </div>

    <div class="form-group">
        <label for="login">Teléfono</label>
        <input class="form-control" [class.is-invalid]="hasError('phone')" id="phone" formControlName="phone">
        <div *ngIf="hasError('phone')" class="invalid-feedback">{{getErrorText('phone')}}</div>
    </div>

    <div *ngIf="errorMessage" class="invalid-feedback">{{errorMessage}}</div>

    <div class="btn-group ">
        <button class="btn btn-primary " (click)="submitForm() " [disabled]="form.invalid">Guardar</button>
        <button class="btn btn-light " [routerLink]="[ '/'] ">Cancelar</button>
    </div>
</form>
