// react-ts/src/views/profile/Profile.js
import React from "react";
import { connect } from "react-redux";
import { updateBasicInfo, updateProfilePicture, getCurrentProfile, getPictureUrl } from "../../api/profileApi";
import { getProvinces } from "../../api/provincesApi";
import CommonComponent from "../../tools/CommonComponent";
import '../../styles.css';
import ImageUpload from "../../tools/ImageUpload";
import ErrorLabel from "../../tools/ErrorLabel";

class StateProfile extends CommonComponent {
    constructor(props) {
        super(props)

        this.updateClick = this.updateClick.bind(this)
        this.uploadPicture = this.uploadPicture.bind(this)

        this.state = {
            name: "",
            province: "",
            email: "",
            address: "",
            phone: "",
            picture: "",
            provinces: []
        }

        this.getProvinces()
        this.loadProfile()
    }

    getProvinces() {
        this.props.getProvinces().then(result => {
            this.setState({
                provinces: result
            })
        }).catch(error => {
            this.processRestValidations(error.response.data)
        })
    }

    loadProfile() {
        this.props.getCurrentProfile().then(result => {
            this.setState(result)
        }).catch(error => {
            this.processRestValidations(error.response.data)
        })
    }

    uploadPicture(image) {
        this.props.updateProfilePicture({
            image: image
        }).then(result => {
            this.setState({
                picture: result.id
            })
        }).catch(error => {
            this.processRestValidations(error.response.data)
        })
    }

    updateClick() {
        this.cleanRestValidations()
        if (!this.state.name) {
            this.addError("name", "No puede estar vacío")
        }
        if (!this.state.email) {
            this.addError("email", "No puede estar vacío")
        }
        if (this.hasErrors()) {
            this.forceUpdate()
            return
        }

        this.props.updateBasicInfo(
            {
                name: this.state.name,
                province: this.state.province,
                email: this.state.email,
                address: this.state.address,
                phone: this.state.phone
            }
        ).then(result => {
            this.props.history.push('/')
        }).catch(error => {
            this.processRestValidations(error.response.data)
        })
    }

    render() {
        return (
            <div className="global_content">
                <h2 className="global_title">Actualizar Perfil</h2>

                <form>
                    <div className="form-group">
                        <label>Nombre</label>
                        <input id="name" value={this.state.name} type="text" onChange={this.updateState} className={this.getErrorClass("name", "form-control")}></input>
                        <ErrorLabel error={this.getErrorText('name')} />
                    </div>

                    <div className="form-group">
                        <label>Profile Picture</label>
                        <ImageUpload src={getPictureUrl(this.state.picture)}
                            onChange={this.uploadPicture} />
                        <ErrorLabel error={this.getErrorText('name')} />
                    </div>

                    <div className="form-group">
                        <label>Email</label>
                        <input id="email" value={this.state.email} type="text" onChange={this.updateState} className={this.getErrorClass("email", "form-control")}></input>
                        <ErrorLabel error={this.getErrorText('email')} />
                    </div>

                    <div className="form-group">
                        <label>Provincia</label>
                        <select
                            value={this.state.province}
                            onChange={(e) => this.setState({ province: e.target.value })}
                            className={this.getErrorClass("email", "form-control")}>
                            {this.state.provinces.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}
                        </select>
                        <ErrorLabel error={this.getErrorText('province')} />
                    </div>

                    <div className="form-group">
                        <label>Direcci&oacute;n</label>
                        <input id="address" value={this.state.address} type="text" onChange={this.updateState} className={this.getErrorClass("address", "form-control")}></input>
                        <ErrorLabel error={this.getErrorText('address')} />
                    </div>

                    <div className="form-group">
                        <label>Tel&eacute;fono</label>
                        <input id="phone" value={this.state.phone} type="text" onChange={this.updateState} className={this.getErrorClass("phone", "form-control")}></input>
                        <ErrorLabel error={this.getErrorText('phone')} />
                    </div>

                    <div hidden={!this.errorMessage} class="alert alert-danger" role="alert">{this.errorMessage}</div>

                    <div className="btn-group ">
                        <button className="btn btn-primary" onClick={this.updateClick}>Actualizar</button>
                        <button className="btn btn-light" onClick={this.goHome} >Cancelar</button >
                    </div >
                </form >
            </div>
        )
    }
}

const Profile = connect(
    null,
    (dispatch) => {
        return {
            updateBasicInfo: user => updateBasicInfo(user),
            getCurrentProfile: _ => getCurrentProfile(),
            getProvinces: _ => getProvinces(),
            updateProfilePicture: payload => updateProfilePicture(payload),
            getPictureUrl: _ => getPictureUrl()
        };
    }
)(StateProfile);

export default Profile

// angular/src/app/profile/profile.component.ts
import { Component, OnInit } from '@angular/core';
import { FormControl, FormGroup, Validators } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { environment } from 'src/environments/environment';
import { Province, ProvinceService } from '../province/province.service';
import { BasicFromGroupController } from '../tools/error.form';
import { ImageService } from '../image/image.service';
import { Profile, ProfileService } from './profile.service';

@Component({
  selector: 'app-perfil',
  templateUrl: './profile.component.html'
})
export class ProfileComponent extends BasicFromGroupController implements OnInit {
  newImage: string;
  provinces: Province[];
  profile: Profile;

  form = new FormGroup({
    name: new FormControl('', [Validators.required]),
    picture: new FormControl('/assets/select_image.png'),
    email: new FormControl('', [Validators.required]),
    address: new FormControl('', [Validators.required]),
    phone: new FormControl('', [Validators.required]),
    province: new FormControl('', [])
  });

  constructor(
    private provinceService: ProvinceService,
    private profileService: ProfileService,
    private imageService: ImageService,
    private route: ActivatedRoute,
    private router: Router
  ) {
    super();
    this.profile = {
      name: '',
      email: '',
      province: '',
      address: '',
      picture: '',
      phone: ''
    };
  }

  updateImage(imagen: string) {
    if (imagen.indexOf(environment.serverBase) < 0) {
      this.newImage = imagen;
    }
  }

  async ngOnInit() {
    try {
      this.provinces = await this.provinceService.getProvinces();
      this.profile = await this.profileService.findProfile();
      this.form.get('name').setValue(this.profile.name);
      this.form.get('email').setValue(this.profile.email);
      this.form.get('address').setValue(this.profile.address);
      this.form.get('phone').setValue(this.profile.phone);
      if (this.profile.province) {
        this.form.get('province').setValue(this.profile.province);
      }
      if (this.profile.picture) {
        this.form.get('picture').setValue(this.imageService.imageUrl(this.profile.picture));
      }
    } catch (error) {
      this.processRestValidations(error);
    }
  }

  async submitForm() {
    this.cleanRestValidations();

    try {
      if (this.newImage) {
        const imagen = await this.imageService.saveImage({ image: this.newImage });
        this.profile.picture = imagen.id;
      }

      this.profile.address = this.form.get('address').value;
      this.profile.name = this.form.get('name').value;
      this.profile.email = this.form.get('email').value;
      this.profile.province = this.form.get('province').value;
      this.profile.phone = this.form.get('phone').value;

      await this.profileService.saveProfile(this.profile);
      this.router.navigate(['/']);
    } catch (error) {
      this.processRestValidations(error);
    }
  }
}

<h2>Perfil</h2>

<form [formGroup]="form">

    <div class="form-group">
        <label for="login">Nombre</label>
        <input class="form-control" [class.is-invalid]="hasError('name')" id="name" formControlName="name">
        <div *ngIf="hasError('name')" class="invalid-feedback">{{getErrorText('name')}}</div>
    </div>

    <div class="form-group">
        <label for="name">Imagen</label><BR>

        <app-file-upload allowedTypes="image/*" uploadButtonText="Upload File" formControlName="picture"
            (ngModelChange)="updateImage($event)">
        </app-file-upload>

        <div *ngIf="hasError('picture')" class="invalid-feedback">{{getErrorText('picture')}}</div>
    </div>

    <div class="form-group">
        <label for="login">Email</label>
        <input class="form-control" [class.is-invalid]="hasError('email')" id="email" formControlName="email">
        <div *ngIf="hasError('email')" class="invalid-feedback">{{getErrorText('email')}}</div>
    </div>

    <div class="form-group">
        <label for="login">Provincia</label>
        <select class="form-control" [class.is-invalid]="hasError('province')" formControlName="province">
            <option *ngFor="let item of provinces" [value]="item.id">{{item.name}}</option>
        </select>

        <div *ngIf="hasError('province')" class="invalid-feedback">{{getErrorText('province')}}</div>
    </div>

    <div class="form-group">
        <label for="login">Dirección</label>
        <input class="form-control" [class.is-invalid]="hasError('address')" id="address" formControlName="address">
        <div *ngIf="hasError('address')" class="invalid-feedback">{{getErrorText('address')}}</div>
    </div>

    <div class="form-group">
        <label for="login">Teléfono</label>
        <input class="form-control" [class.is-invalid]="hasError('phone')" id="phone" formControlName="phone">
        <div *ngIf="hasError('phone')" class="invalid-feedback">{{getErrorText('phone')}}</div>
    </div>

    <div *ngIf="errorMessage" class="invalid-feedback">{{errorMessage}}</div>

    <div class="btn-group ">
        <button class="btn btn-primary " (click)="submitForm() " [disabled]="form.invalid">Guardar</button>
        <button class="btn btn-light " [routerLink]="[ '/'] ">Cancelar</button>
    </div>
</form>
